### PR TITLE
update InvalidArgumentException usage in Application::route()

### PR DESCRIPTION
**Pull request by samsonasik**
per my comment in https://github.com/zendframework/zend-expressive/pull/20/files#r36340269

### CODE REVIEW

**Comment by samsonasik** [comment]
ping @weierophinney

**Comment by samsonasik** [comment]
I've added unit tests for it.

**Comment by weierophinney** [comment]
@samsonasik Saw your comment on #20 first, and created and merged #24 in response already!

**Comment by samsonasik** [comment]
so fast :+1:

**Pull request closed without merging**
