### PR TITLE
[Doc]In Composer Serve Command " was missing

### PR DESCRIPTION
**Pull request by zf2timo**

### CODE REVIEW

**Comment by samsonasik** [comment]
@zf2timo the doc moved to another folder, plase rebase

**Comment by zf2timo** [comment]
@samsonasik How can i do a rebase to a changed file path?

**Comment by samsonasik** [comment]
Should do-able with this steps:
```
git checkout master
git remote add upstream git://github.com/zendframework/zend-expressive.git
git pull upstream master
git checkout composer-serve-fix
git rebase master
```
you will get conflict, now, you can remove `doc/book/quick-start.md` completely, and then, modify moved quick-start, now, next steps are:
```
git add .
git rebase --continue
git push --force origin composer-serve-fix
```

**Comment by zf2timo** [comment]
@samsonasik Thank you for the instructions.

But after the `git rebase master` i don't receive a conflict and also there are no changes in my repository.

**Comment by samsonasik** [comment]
if master changed, the changes should applied to `composer-serve-fix` when do rebase master, if everything ok, should do able just do:
```
git push --force origin composer-serve-fix
```
if still not work, probably just do new pull request.

**Comment by zf2timo** [comment]
@samsonasik i created a new PR in #289

**Pull request closed without merging**
