### PR TITLE
New style for homepage

### PR DESCRIPTION
**Pull request by baptistemanson**
This PR contains cosmetic changes on then homepage. 
[Here is a snapshot on imgur](http://imgur.com/fKbUGVa).
The icons have been changed, realigned some elements, changed the font, removed the border radius, cleanup the usage of the containers and rows.

It goes with the PR on the https://github.com/baptistemanson/zf-mkdoc-theme named new-style-upgrade.

- The icons are all free + CC except one which has a commercial license - which I transfer to the project.
- The specific CSS for this homepage has been isolated in its own file in the theme folder called zend-expressive. I could have named it better, and probably will later.

Thanks!

### CODE REVIEW

**Comment by weierophinney** [comment]
@baptistemanson This looks like you merged develop to master, pushed, but did not add any commits...

**Comment by weierophinney** [comment]
@baptistemanson I went searching for the commits on your own repository, and cannot find them there, either...

**Comment by weierophinney** [comment]
@baptistemanson Steps you should take:

- Fetch latest changes from this repository (I merged some CSS changes in #299): `git fetch upstream`
- Rebase your `new-style-for-homepage` branch against master: `git rebase upstream/master`.
- When you add your files and changes, you can put any component-specific CSS changes into the `doc/book/css/zend-expressive.css` file.

I'm going to create an alternate PR for the short-term that adds the install instructions into the jumbotron, as I'm not sure when you'll be available today. :smile:

**Comment by baptistemanson** [comment]
I'll do this morning, thanks sorry for the confusion.

**Comment by baptistemanson** [comment]
I will redo the PR then.

**Pull request closed without merging**
