### PR TITLE
Fixes zend-psr7bridge composer decription

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by ojhaujjwal** [comment]
:-1:

**Comment by samsonasik** [comment]
why :-1: ?

**Comment by ojhaujjwal** [comment]
I think that if somebody wants to use `Zend\Expressive\Router\Zf2`, they should know that they need to install package `zendframework/zend-psr7bridge`. I think it is good now.

**Comment by samsonasik** [comment]
ok ;)

**Pull request closed without merging**
