### PR TITLE
h

### PR DESCRIPTION
**Pull request by chusasix**
h

### CODE REVIEW

**Comment by Ocramius** [comment]
@chusasix can you please stop opening these? Especially with no description... Also, seems like you are using @modess' repo to do that :-\

**Comment by modess** [comment]
My repo certainly have nothing to do with zend expressive or any PR to it. Is there anything I can do to prevent this?

**Comment by Ocramius** [comment]
@modess I know, and no, you can't do anything to prevent it. Just trying to figure out if @chusasix is doing these by mistake, or if it's a bot that needs banning.

**Comment by xtreamwayz** [comment]
Doesn't look like a bot given his commit history.

**Comment by chusasix** [comment]
I'm sorry just say that I'm a rookie in github

2016-12-14 14:48 GMT+01:00 Geert Eltink <notifications@github.com>:

**Pull request closed without merging**
