### PR TITLE
Documentation build chain for gh-pages

### PR DESCRIPTION
**Pull request by weierophinney**
This pull-request provides a new documentation build chain to allow publishing to gh-pages for commits to master. It serves as a sandbox for how we can do the ZF component documentation going forward as well.

It implements the following:

- Removes all usage of [bookdown](http://bookdown.io). Unfortunately, I found templating with it far too cumbersome, and it is missing features we could use (e.g. sidebar nav, top nav, etc.), but which would take some time to develop.
- Implements a more thorough [MkDocs](http://www.mkdocs.org) build configuration, with fewer top-level items, more nesting, and specifying configuration features such as custom templates, extension directives to disable pygments highlighting, etc.
- Reorganizes the documentation a fair bit to provide more natural groupings.

I implemented a custom MkDocs theme based on [Cinder](http://sourcefoundry.org/cinder/), which I have proposed at [weierophinney/zf-mkdoc-theme](https://github.com/weierophinney/zf-mkdoc-theme). You can see it in action at https://zendframework.github.io/zend-expressive/

~~At this time, I still need to test the travis -> gh-pages workflow, and, for that reason, I'm marking it as a WIP. If it works as expected, I'll update the issue to indicate readiness.~~

### CODE REVIEW

**Comment by weierophinney** [comment]
Awesome. I evidently branched from develop. *sigh*

Fortunately, the file changes shown are accurate; master and develop are in sync currently.

**Comment by weierophinney** [comment]
Ping @ezimuel  and @GeeH — curious to hear your opinions.

**Comment by xtreamwayz** [comment]
Looks like its easy to use.

About the theme: You might want to add the previous and next links at the bottom of the page as well. Although the top navbar is static, on smaller devices the nav links are hidden behind the hamburger icon.

**Comment by akrabat** [comment]
I like it, too.

**Comment by RalfEggert** [comment]
I like it as well. :+1: 

But it seems that the search does not work. If it doesn't work it shouldn't be shown in the menu. And maybe its possible to add the ZF logo?

**Comment by froschdesign** [comment]
@all
I think, this is no the right place to discuss the template. The topic should be the build chain.

@weierophinney 
With Bookdown it is very easy to create a complete documentation with all components. ("[Remote Content](http://bookdown.io/advanced/remote.html#3.1)")
How does it work in MkDocs or is an own build script needed?

>  it is missing features we could use (e.g. sidebar nav, top nav, etc.), but which would take some time to develop.

I have a test script for a navigation. I will invest some work over the weekend and give you a feedback.

@RalfEggert 
> But it seems that the search does not work.

This is a only a JavaScript problem ("base_url is not defined"), which can be fixed quickly.

**Comment by weierophinney** [comment]
@froschdesign The plan that @ezimuel and I have been discussing is to host docs for components on github pages, and to create a landing page for the organization. This vastly simplifies the problems of keeping the documentation up-to-date — and also means that the ability of merging remote documentation is no longer a requirement.

As such, I definitely think we can discuss the template. In particular, suggestions on navigation are very welcome, and I'll be looking into how to address the various suggestions already made.

**Comment by froschdesign** [comment]
@weierophinney 
> The plan that @ezimuel and I have been discussing is to host docs for components on github pages, and to create a landing page for the organization.

That's good to know and a nice idea. :+1: 

> In particular, suggestions on navigation are very welcome, and I'll be looking into how to address the various suggestions already made.

For suggestions and extensions (PRs) should we use your ["zf-mkdoc-theme" repository](https://github.com/weierophinney/zf-mkdoc-theme)? Or is there a plan to migrate the theme to the [zendframework/documentation repository](https://github.com/zendframework/documentation)?

**Comment by sandrokeil** [comment]
@froschdesign It is possible to integrate your navigation script in bookdown? 

Hosting on GitHub pages with Travis integration is really a good idea. :+1:

**Comment by weierophinney** [comment]
The latest commits to this update the build chain to use the `--user` flag when installing pip packages; this ensures permissions are correct. In order to use those packages, you also need to export `$HOME/.local/bin`. Finally, I decided to cache `$HOME/.local` between invocations, to speed up builds.

I've tested this at https://github.com/weierophinney/zf-docs-toolchain-experiment, and verified it works correctly.

At this point, I'll turn to some of the layout suggestions from the comments.

**Comment by weierophinney** [comment]
@froschdesign —

> For suggestions and extensions (PRs) should we use your "zf-mkdoc-theme" repository? Or is there a plan to migrate the theme to the zendframework/documentation repository?

For now, we can use my zf-mkdoc-theme repo; I'll be moving this into the zendframework org and/or incorporating it as part of the zendframework/documentation repo eventually. I wanted to do it separately at first while experimenting with the approach; I think the results are proving worthwhile, and the effort needed to make things work has been minimal, which makes me happy.

@sandrokeil — The issues I had with bookdown were:

- I was going to need to come up with a "theme" from scratch, as the only bookdown examples I've seen are the bookdown site and the Aura docs, none of which match my ideas for visual presentation.
- I've not seen examples of topnav + sidenav in bookdown, and, in point of fact, there are open issues for these on the bookdown repo already. I started looking into it, but I felt the amount of effort required was going to be a distraction from getting the release ready.

MkDocs is mature, and we were already using it via a conversion layer (I wrote a script that converts bookdown.json to mkdocs.yml early on) to render on rtfd.org. It has a fairly rich ecosystem, which meant I was also able to find themes quickly that matched what I wanted for visual presentation. At this point, I've proven you can integrate it into a Travis-CI chain without much problem, too. As such, I say, "use the tool that gets the job done."

**Comment by sandrokeil** [comment]
> use the tool that gets the job done.

@weierophinney Yes, that's it.

For those who looking for another extended bookdown theme, look at [tobiju/bookdown-bootswatch-templates](https://github.com/tobiju/bookdown-bootswatch-templates). But top and site nav are missing.

**Comment by weierophinney** [comment]
Search is now working; it was an issue with the theme, which I've now corrected.

**Comment by weierophinney** [comment]
Breadcrumbs and next/prev pager implemented. Breadcrumbs are not terribly useful, as we don't have "index" pages for sections yet; I'll see if I can figure out how to do that with mkdocs. Results are posted, though, so please review.

Next items on my list are:

- move intro -> index pages (intro was a convention from bookdown, as index pages were always ToCs)
- add zf logo in topnav, linking to zf site.
- make initial landing page more of a "marketing" page, with links to most relevant doc pages.

**Comment by weierophinney** [comment]
ZF logo is now used in the navbar and as the favicon. (ping @RalfEggert)

It looks like MkDocs shares the same issue/feature as bookdown in relation to index pages for subsections; essentially, they cannot be done. As such, the last remaining item (currently) is to update the landing page to make it more of a "why you should use Expressive" message.

**Comment by RalfEggert** [comment]
:+1:

**Comment by weierophinney** [comment]
Rebased against master, which was my original plan all along.

**Comment by weierophinney** [comment]
Okay, feature is complete. The latest iteration provides custom landing page content that is swapped into the landing page generated by mkdocs, and which is more "marketing" oriented (why use it? how do you use it? etc.), with links to relevant deeper pages of the documentation.

**Comment by weierophinney** [comment]
Pinging @akrabat, @GeeH, and @RalfEggert for review!

**Comment by weierophinney** [comment]
The only additional change I'm considering making, and it can be made after merge, is to push the `doc/*.sh` and `doc/swap_index.php` scripts into the documentation or zf-mkdoc-theme packages. They are re-usable already, which would allow us to download them when we're ready to deploy documentation only; they could even be cached between invocations.

The benefit to doing so is that if we want to make a change to the build process at any point, we can make it across every repository at once, instead of needing to push piecemeal.

**Comment by RalfEggert** [comment]
@weierophinney 

Looks really great and the intro page is a big improvement for the docs. Are you planning this for every ZF component?

Anyway, just a little, small detail. On my smart phone the hamburger icon is not shown in the portrait mode. It is only shown in the landscape mode. I am using an iPhone 5s.

Portrait | Landscape
------------ | -------------
img_8585 | img_8586

Maybe a front end guy knows why this happens?

**Comment by xtreamwayz** [comment]
> On my smart phone the hamburger icon is not shown in the portrait mode. It is only shown in the landscape mode. I am using an iPhone 5s.

That's because the expressive-skeleton screenshot is too big. Ideally you want to add a ``img-responsive`` class to it to make it responsive (auto-size). But if that's not possible, forcing all images to be responsive might work:

```css
img {
    max-width: 100%;
    height: auto;
}
```

**Comment by RalfEggert** [comment]
@xtreamwayz 

I guess that might solve the issue...

**Comment by GeeH** [comment]
It works well, my only (massive) concern is that all the current repositories have bookdown.json - will I need to change this for every repo for this new tool?

**Comment by weierophinney** [comment]
@GeeH I have a tool for that already (https://github.com/phly/bookdown2mkdocs), and we can do it individually as we prepare each component for gh-pages launch. (I was already using that tool in this repo to create a `mkdocs.yml` so we could use rtfd.org, and I use it on the SM, EM, and zend-code repos, too.)

**Comment by weierophinney** [comment]
@RalfEggert Thanks for the feedback, and @xtreamwayz for the hint as to how to fix it; have the change pushed already.

**Comment by RalfEggert** [comment]
@weierophinney 

And I can confirm that it works now! :+1:

**Comment by weierophinney** [comment]
I've moved the deploy/build scripts into the zf-mkdoc-theme at this time, which allows us to re-use them across components. The latest commits have working Travis configuration for downloading, invoking, and caching the theme and build tools.

My plan at this point is:

- [ ] to move the theme into the zendframework organization
- [ ] to update the travis configuration to download the theme from the new repo
- [ ] to squash commits in this repo to remove some of the noise (such as the changes to the build tools over time, particularly as they're now in a different repo)

At that point, I think I can go ahead and merge, based on the feedback on the pull request so far.

**Comment by akrabat** [comment]
PR looks good to me.

**Comment by weierophinney** [comment]
And we have our first automated commit — f0b7285b !

**Pull request merged**
