### PR TITLE
Update v3 docs

### PR DESCRIPTION
**Pull request by xtreamwayz**
- [x] Is this related to documentation?

### CODE REVIEW

**Comment by webimpress** [comment]
@xtreamwayz just only one note, we should probably update also `description` in `composer.json`, now we have there: `PSR-7 Middleware Microframework based on Stratigility` and any single word about PSR-15 ;-)

**Comment by froschdesign** [comment]
…and the description of this repository!

/cc @weierophinney

**Comment by xtreamwayz** [comment]
> …and the description of this repository!

Same for the skeleton repo.

**Comment by webimpress** [comment]
> > …and the description of this repository!
>
> Same for the skeleton repo.

... and stratigility ?

**Comment by weierophinney** [comment]
Thanks, @xtreamwayz!

**Pull request merged**
