### PR TITLE
Make InvalidMiddlewareException more verbose

### PR DESCRIPTION
**Pull request by nightlinus**
Add $middleware to exception message if it is string to know problem middleware.

### CODE REVIEW

**Comment by Ocramius** [comment]
@nightlinus this change is unclear to me. Can you add a test case showing why this was done?

**Comment by nightlinus** [comment]
Ok, i will add. It is usefull when you use invokable class as middleware and it is not loadable via autoload.
for example in config:
```php
return [
  'path' => '/',
  'middleware' => ShowMain::class,
];
```
Here if something is wrong with autoload you get just ```Unable to resolve middleware "string[Scalar]"``` to a callable'.

**Comment by harikt** [comment]
@nightlinus it looks to me your class `ShowMain` is not callable. And the error you got seems to be correct to me.

**Comment by nightlinus** [comment]
It is callable, but not autoloadable.

**Comment by harikt** [comment]
@nightlinus if that is the case, I don't think you change will mention this class is not auto loadable.

**Comment by nightlinus** [comment]
But it will tell with what class there is a problem.

**Comment by harikt** [comment]
ok. cool. Thank you for the explanation @nightlinus .

**Pull request closed without merging**
