### PR TITLE
Using a Pimple 3 wrapper as an example of a Container-Interop container

### PR DESCRIPTION
**Pull request by Sam-Burns**
Using samburns/pimple3-containerinterop as example of DI container

### CODE REVIEW

**Comment by Sam-Burns** [comment]
Ref. https://github.com/zendframework/zend-expressive/issues/129.  \cc @weierophinney

**Comment by weierophinney** [comment]
@Sam-Burns Awesome! Can you also do a PR against https://github.com/zendframework/zend-expressive-skeleton ? Relevant files are:

- https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/config.php#L7
- https://github.com/zendframework/zend-expressive-skeleton/blob/master/src/ExpressiveInstaller/Resources/config/container-pimple-interop.php

As I noted on #129, I can then do some integration testing based on your patch.

Thanks!

**Comment by xtreamwayz** [comment]
@weierophinney As explained in #129 I'm wondering if we should use another package that is extending Pimple in stead of placing it in another class. That way you won't loose all other functionality from Pimple and it's most likely easier to convert to a new Pimple release which supports container-interop.

**Comment by weierophinney** [comment]
Closed in favor of #237. No hard feelings, @Sam-Burns — I just liked the approach of extending the pimple container better.

**Comment by Sam-Burns** [comment]
@weierophinney it was an honour just to be nominated ;-)

**Pull request closed without merging**
