### PR TITLE
change service naming: Zend\Expressive\FinalHandler to Zend\Stratigility\FinalHandler

### PR DESCRIPTION
**Pull request by samsonasik**
as <code>FinalHandler</code> class is in <code>Zend\Stratigility</code> components.

### CODE REVIEW

**Comment by weierophinney** [comment]
I'm going back and forth on this. On the one hand, yes, the class is defined in Stratigility. On the other, we may very well provide our own final handler before we're done (to provide templated error pages). Still mulling it over.

**Comment by samsonasik** [comment]
ok, just note, if we will use own final class, then <code>Application::getFinalHandler()</code> should return <code>Zend\Expressive\FinalHandler</code> too ;)

**Comment by weierophinney** [comment]
> ok, just note, if we will use own final class, then Application::getFinalHandler() should return Zend\Expressive\FinalHandler too ;)

It doesn't need to, actually. It just needs to return a `callable` to use for when the middleware stack is exhausted; `Zend\Stratigility\FinalHandler` is just a default implementation, but it could even be a closure (we use closures in many of the tests). That's the other reason why the service name is largely irrelevant.

**Comment by weierophinney** [comment]
Closing. FinalHandler may be a callable. As such, the service name is not and will not have a 1:1 mapping to an existing class.

**Pull request closed without merging**
