### PR TITLE
Fixed config factory typos in docs

### PR DESCRIPTION
**Pull request by chris2039**

### CODE REVIEW

**Comment by samsonasik** [comment]
linked with #106

**Comment by samsonasik** [comment]
linked with #104

**Comment by weierophinney** [comment]
I'm going to make one slight change to this: the factory returns Config objects, so I'll alias `Factory` to `ConfigFactory` to make it more apparent what the code is returning.

**Comment by chris2039** [comment]
Sounds good I was thinking the same too.

**Pull request merged**
