### PR TITLE
Fix typo in the docbloc for the @param value

### PR DESCRIPTION
**Pull request by ncou**
correction for the @param value.

### CODE REVIEW

**Comment by ncou** [comment]
related to the issue : https://github.com/zendframework/zend-expressive/issues/662

**Comment by Xerkus** [comment]
Please also update ignored phpstan error pattern in phpstan.neon https://travis-ci.org/zendframework/zend-expressive/jobs/538575283#L726

**Comment by ncou** [comment]
Oouups. It should be fine now.

**Comment by Xerkus** [comment]
@ncou thank you

**Pull request merged**
